apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: docket-api
    app.kubernetes.io/part-of: open-case-filing-system
    app.kubernetes.io/component: api
  name: docket-api
  namespace: dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: docket-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: docket-api
    spec:
      serviceAccountName: docket-api-sa
      containers:
        - name: docket-api
          image: ghcr.io/federal-courts-software-factory/open-case-filing-system/web:sha-08b344e@sha256:cf28761b7a1cffb388f1a5d7ab7b35f9a1c3a1b6ef83924457031918231de1e4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi

