apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: open-case-filing-system
    app.kubernetes.io/component: api
  name: web
  namespace: dev
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: web-sa
      containers:
      - image: ghcr.io/federal-courts-software-factory/open-case-filing-system/web:sha-08b344e@sha256:cf28761b7a1cffb388f1a5d7ab7b35f9a1c3a1b6ef83924457031918231de1e4
        name: web
        imagePullPolicy: Always
        ports:

