apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-previews-web
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: federal-courts-software-factory
        # The Github repository
        repo: ocfs-environment
      requeueAfterSeconds: 1800
  template:
    metadata:
      name: 'ocfs-{{branch}}-{{number}}'
    spec:
      destination:
        namespace: 'preview-{{branch}}'
        server: 'https://kubernetes.default.svc'
      project: demo
      source:
        path: clusters/environment/appsets/preview/web
        repoURL: 'https://github.comfederal-courts-software-factory/ocfs-environment.git'
        targetRevision: HEAD
        helm:
          parameters:
            - name: namespace
              value: 'preview-{{branch}}'
            - name: version
              value: '{{head_sha}}'
            - name: test
              value: '{{ARGOCD_APP_SOURCE_PATH}}'
            - name: image
              value: web
            - name: name
              value: pr-web
      # (7)
      syncPolicy:
        automated:
          selfHeal: true

# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: myapps
# spec:
#   generators:
#   - pullRequest:
#     # ...
#   template:
#     metadata:
#       name: 'myapp-{{branch}}-{{number}}'
#     spec:
#       source:
#         repoURL: 'https://github.com/myorg/myrepo.git'
#         targetRevision: '{{head_sha}}'
#         path: kubernetes/
#         kustomize:
#           nameSuffix: {{branch}}
#           commonLabels:
#             app.kubernetes.io/instance: {{branch}}-{{number}}
#           images:
#           - ghcr.io/myorg/myrepo:{{head_sha}}
#       project: "my-project"
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: default