apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  #policy.default: role:admin
  policy.csv: |
    p, federal-courts-software-factory/software-engineers, role:admin
    g, federal-courts-software-factory/infrastructure, role:admin
  scopes: '[email,groups]'
